export const ROUTES = {
    home: "/login-mobile",
    login_cnic: "/login-cnic",
    signup: "/signup",
    forgotpassword: "/forgot-password",
    resetpassword: "/reset-password",
    dashboard: "/dashboard",
    applicant_details: "/applicant-details",
    applicant_address: "/applicant-address",
    notification_inbox: "/notification-inbox",
    user_profile: "/user-profile",
    help: "/help",
    contact_us: "/contact-us",
    faq: "/faq",
    terms_conditions: "/terms-conditions",
    privacy_policy: "/privacy-policy",
    services: "/services",
    service_details: "/services/service-details",
    reports: "/reports",
    add_report: "/add-report",
    view_complain: "/view-complain",
    add_other_complaints: "/other-complaints",
};
